Fix building
Now build works, and I can finally adjust code to make all dependencies
work.

TODO:
src/YHttpWidgetsActionHandler.cc:86:21: error: ‘class YPushButton’ has
no member named ‘activate’
             button->activate();
Need to migrate required changes to libyui base package to make
interfaces to work.