Include YMenuWidget before it is used
otherwise swig 4.0.2 says

    /usr/include/yui/YMenuBar.h:50: Warning 401: Base class 'YMenuWidget' undefined.
    /usr/include/yui/YMenuWidget.h:39: Warning 401: 'YMenuWidget' must be defined before it is used as a base class.

and then it fails at runtime

    self.menubar.resolveShortcutConflicts()
    AttributeError: 'YMenuBar' object has no attribute 'resolveShortcutConflicts'