src: Replace using sys/errno.h with errno.h
sys/errno.h is no longer the right place for this file

error: #warning redirecting incorrect #include <sys/errno.h> to <errno.h> [-Werror=cpp]

Signed-off-by: Khem Raj <raj.khem@gmail.com>